Controllers/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Budgeting.Data;
using Budgeting.Models;
using FastExcel;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Budgeting.Controllers
{
    public class BudgetController : Controller
    {
        private readonly BudgetingContext _context;

        public BudgetController(BudgetingContext context)
        {
            _context = context;
        }

        private IEnumerable<BudgetEntry> ParseBudgetXML(string fileName)
        {
            var currentEntriesTask = _context.BudgetEntry.ToListAsync();
            currentEntriesTask.Wait();
            var currentEntries = currentEntriesTask.Result;
            List<BudgetEntry> entries = new List<BudgetEntry>();
            List<string> isExpenceNames = new List<string>() { "C", "D", "E", "F", "G" };
            using (FastExcel.FastExcel fastExcel = new FastExcel.FastExcel(new FileInfo(fileName), true))
            {
                var sheet = fastExcel.Worksheets[0];
                sheet.Read();

                List<Row> rows = sheet.Rows.ToList();
                foreach (Row row in rows)
                {
                    if (row.RowNumber == 1) continue;
                    List<Cell> columns = row.Cells.ToList();
                    BudgetEntry budgetEntry = new BudgetEntry();
                    budgetEntry.VariableCosts = false;
                    foreach(Cell cell in columns)
                    {
                        Console.WriteLine($"CellColumn: {cell.ColumnName}, Value {cell.Value}");
                        switch (cell.ColumnName)
                        {
                            case "A":
                                budgetEntry.Name = (string)cell.Value;
                                break;
                            case "H":
                                budgetEntry.FromCreditcard = true;
                                break;
                            case "I":
                            case "P":
                                budgetEntry.ToSharedAccount = true;
                                break;
                            case "Q":
                                budgetEntry.Category = (string)cell.Value;
                                break;
                            case "C":
                            case "K":
                                budgetEntry.TimeAmount = TimeAmount.FOURWEEK;
                                break;
                            case "D":
                            case "L":
                                budgetEntry.TimeAmount = TimeAmount.MONTH;
                                break;
                            case "E":
                            case "M":
                                budgetEntry.TimeAmount = TimeAmount.QUARTERYEAR;
                                break;
                            case "F":
                            case "N":
                                budgetEntry.TimeAmount = TimeAmount.HALFYEAR;
                                break;
                            case "G":
                            case "O":
                                budgetEntry.TimeAmount = TimeAmount.YEAR;
                                break;
                        }
                        switch (cell.ColumnName)
                        {
                            case "C":
                            case "D":
                            case "E":
                            case "F":
                            case "G":
                            case "J":
                            case "K":
                            case "L":
                            case "M":
                            case "N":
                            case "O":
                                budgetEntry.IsIncome = !isExpenceNames.Contains(cell.ColumnName);
                                string moneyValue = (string)cell.Value;
                                moneyValue = moneyValue.Replace(".", ",");
                                budgetEntry.MoneyAmount = decimal.Parse(moneyValue); 
                                break;
                        }
                    }
                    var existingEntry = currentEntries.Find(be => be.Name.Equals(budgetEntry.Name));
                    if(existingEntry != null)
                    {
                        if(Math.Abs(existingEntry.MoneyAmount) != budgetEntry.MoneyAmount)
                        {
                            budgetEntry.Description = "orange";
                        }
                        else
                        {
                            budgetEntry.Description = "gray";
                        }
                    }
                    else
                    {
                        budgetEntry.Description = "green";
                    }
                    entries.Add(budgetEntry);
                }
            }
            return entries;
        }

        // POST: Budget/Import
        public async Task<IActionResult> Import(IFormFile ImportFile)
        {
            if (ImportFile.Length > 0)
            {
                var filePath = Path.GetTempFileName();

                using (var stream = System.IO.File.Create(filePath))
                {
                    await ImportFile.CopyToAsync(stream);
                }
                ViewBag.FilePath = filePath;
                return View(ParseBudgetXML(filePath));
            }
            return Problem("File is empty");
        }

        // POST: Budget/ImportAccept
        public async Task<IActionResult> ImportAccept(string FilePath)
        {
            var fromImportEntries = ParseBudgetXML(FilePath);
            var currentEntries = await _context.BudgetEntry.ToListAsync();
            foreach(var entry in fromImportEntries)
            {
                entry.Description = ""; 
                if (!entry.IsIncome) entry.MoneyAmount *= -1;
                if(currentEntries.Any(ce => ce.Name == entry.Name))
                {
                    await Console.Out.WriteLineAsync($"Budget entry with the name {entry.Name} already exists");
                } 
                else
                {
                    _context.Add(entry);
                }

            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Budget/List
        public async Task<IActionResult> Index()
        {
            return _context.BudgetEntry != null ?
                        View(await _context.BudgetEntry.ToListAsync()) :
                        Problem("Entity set 'BudgetingContext.BudgetEntry' is null.");
        }

        // GET: Budget/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BudgetEntry == null)
            {
                return NotFound();
            }

            var budgetEntry = await _context.BudgetEntry
                .FirstOrDefaultAsync(m => m.Id == id);
            if (budgetEntry == null)
            {
                return NotFound();
            }

            return View(budgetEntry);
        }

        // GET: Budget/Create
        public IActionResult Create()
        {
            List<string> categories = new List<string>();
            foreach(string? category in _context.BudgetEntry.ToList().Select(b => b.Category).ToList())
            {
                if (category == null) continue;
                if(!categories.Contains(category))
                {
                    categories.Add(category);
                }
            }
            ViewBag.categories = categories;
            return View();
        }

        // POST: Budget/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Category,IsIncome,MoneyAmount,TimeAmount,FromCreditcard,ToSharedAccount,VariableCosts,TransferTime")] BudgetEntry budgetEntry)
        {
            if (ModelState.IsValid)
            {
                if (!budgetEntry.IsIncome)
                {
                    if (budgetEntry.MoneyAmount > 0)
                    {
                        budgetEntry.MoneyAmount *= -1;
                    }
                }
                _context.Add(budgetEntry);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(budgetEntry);
        }

        // GET: Budget/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BudgetEntry == null)
            {
                return NotFound();
            }

            var budgetEntry = await _context.BudgetEntry.FindAsync(id);
            if (budgetEntry == null)
            {
                return NotFound();
            }


            List<string> categories = new List<string>();
            foreach (string? category in _context.BudgetEntry.ToList().Select(b => b.Category).ToList())
            {
                if (category == null) continue;
                if (!categories.Contains(category))
                {
                    categories.Add(category);
                }
            }
            ViewBag.categories = categories;
            return View(budgetEntry);
        }

        // POST: Budget/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Shared/_Layout.cshtml
@{
    System.Globalization.CultureInfo culture = new System.Globalization.CultureInfo("en-US", true);
    culture.NumberFormat.NumberDecimalSeparator = ",";
    System.Threading.Thread.CurrentThread.CurrentCulture = culture;
    System.Threading.Thread.CurrentThread.CurrentUICulture = culture;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Budgeting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Budgeting.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Budgeting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Budget" asp-action="Index">Budget</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BudgetLists" asp-action="Index">BudgetList</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Budgeting - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>